[build]
  command = "npm run prerender"
  functions = "./functions"
  publish = "dist/hotequil/browser"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 301
[[headers]]
    for = "/*"
        [headers.values]
            Cache-Control = "max-age=31536000"
