[build]
  command = "npm run build:ssr"
  functions = "./functions"
  publish = "dist/hotequil/browser"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 301
[[headers]]
    for = "/*"
        [headers.values]
            Cache-Control = "max-age=31536000"
            X-Content-Type-Options = "DENY"
            Content-Security-Policy = "sandbox allow-forms allow-same-origin"
            X-Frame-Options = "SAMEORIGIN"
            X-XSS-Protection = "1; mode=block"
